name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          composer clear-cache
          composer install --no-dev --prefer-dist
          npm ci
          npm run build
          npm run i18n

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@1.5.0
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: wc-cart-pdf
      - name: Upload release asset
        if: |
          steps.semantic.outputs.new-release-published == 'true' &&
          startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
